language: python
python:
- '3.6'
before_install:
- wget -O data/postni_nabiralniki.pdf https://www.posta.si/zasebno-site/Documents/Seznami/Seznam%20po%C5%A1tnih%20nabiralnikov.pdf
- mv data/postni_nabiralniki.json data/postni_nabiralniki_old.json
addons:
  apt:
    packages:
      - ghostscript
install:
- pip install -r py/requirements.txt
script:
- python py/parser.py data/postni_nabiralniki.pdf data/postni_nabiralniki_old.json data/postni_nabiralniki.json
after_success:
- scripts/push_to_git.sh